name: Publish to PyPI

on:
  push:
    tags:
      - v0.5.3(-[0-9]+)?

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Installs dependencies"
        run: |
          python -m pip install flit

      - name: "Build and publish to PyPI"
        run: |
          python -m flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
