name: unit_tests
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { name: Linux-Py39, python: "3.9", os: ubuntu-latest, tox: py }
          - { name: Linux-Py310, python: "3.10", os: ubuntu-latest, tox: py }
          - { name: Linux-Py311, python: "3.11", os: ubuntu-latest, tox: py }
          - { name: Linux-Py312, python: "3.12", os: ubuntu-latest, tox: py }
          - { name: Linux-Py313, python: "3.13", os: ubuntu-latest, tox: py }
          - { name: Style, python: "3.9", os: ubuntu-latest, tox: style }
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.tox }}
